//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.WC.IDAL;
using Apps.Models.WC;
namespace Apps.WC.BLL
{
	public class Virtual_WC_MessageResponseBLL
	{
        [Dependency]
        public IWC_MessageResponseRepository m_Rep { get; set; }

		public virtual List<WC_MessageResponseModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<WC_MessageResponse> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.OfficalAccountId.Contains(queryStr)
								
								
								|| a.MatchKey.Contains(queryStr)
								|| a.TextContent.Contains(queryStr)
								|| a.ImgTextContext.Contains(queryStr)
								|| a.ImgTextUrl.Contains(queryStr)
								|| a.ImgTextLink.Contains(queryStr)
								|| a.MeidaUrl.Contains(queryStr)
								|| a.MeidaLink.Contains(queryStr)
								
								
								|| a.Remark.Contains(queryStr)
								
								
								|| a.CreateBy.Contains(queryStr)
								
								|| a.ModifyBy.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<WC_MessageResponseModel> CreateModelList(ref IQueryable<WC_MessageResponse> queryData)
        {

            List<WC_MessageResponseModel> modelList = (from r in queryData
                                              select new WC_MessageResponseModel
                                              {
													Id = r.Id,
													OfficalAccountId = r.OfficalAccountId,
													MessageRule = r.MessageRule,
													Category = r.Category,
													MatchKey = r.MatchKey,
													TextContent = r.TextContent,
													ImgTextContext = r.ImgTextContext,
													ImgTextUrl = r.ImgTextUrl,
													ImgTextLink = r.ImgTextLink,
													MeidaUrl = r.MeidaUrl,
													MeidaLink = r.MeidaLink,
													Enable = r.Enable,
													IsDefault = r.IsDefault,
													Remark = r.Remark,
													Sort = r.Sort,
													CreateTime = r.CreateTime,
													CreateBy = r.CreateBy,
													ModifyTime = r.ModifyTime,
													ModifyBy = r.ModifyBy,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, WC_MessageResponseModel model)
        {
            try
            {
			    WC_MessageResponse entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new WC_MessageResponse(); 
				entity.Id = model.Id;
				entity.OfficalAccountId = model.OfficalAccountId;
				entity.MessageRule = model.MessageRule;
				entity.Category = model.Category;
				entity.MatchKey = model.MatchKey;
				entity.TextContent = model.TextContent;
				entity.ImgTextContext = model.ImgTextContext;
				entity.ImgTextUrl = model.ImgTextUrl;
				entity.ImgTextLink = model.ImgTextLink;
				entity.MeidaUrl = model.MeidaUrl;
				entity.MeidaLink = model.MeidaLink;
				entity.Enable = model.Enable;
				entity.IsDefault = model.IsDefault;
				entity.Remark = model.Remark;
				entity.Sort = model.Sort;
				entity.CreateTime = model.CreateTime;
				entity.CreateBy = model.CreateBy;
				entity.ModifyTime = model.ModifyTime;
				entity.ModifyBy = model.ModifyBy;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, WC_MessageResponseModel model)
        {
            try
            {
                WC_MessageResponse entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.OfficalAccountId = model.OfficalAccountId;
				entity.MessageRule = model.MessageRule;
				entity.Category = model.Category;
				entity.MatchKey = model.MatchKey;
				entity.TextContent = model.TextContent;
				entity.ImgTextContext = model.ImgTextContext;
				entity.ImgTextUrl = model.ImgTextUrl;
				entity.ImgTextLink = model.ImgTextLink;
				entity.MeidaUrl = model.MeidaUrl;
				entity.MeidaLink = model.MeidaLink;
				entity.Enable = model.Enable;
				entity.IsDefault = model.IsDefault;
				entity.Remark = model.Remark;
				entity.Sort = model.Sort;
				entity.CreateTime = model.CreateTime;
				entity.CreateBy = model.CreateBy;
				entity.ModifyTime = model.ModifyTime;
				entity.ModifyBy = model.ModifyBy;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual WC_MessageResponseModel GetById(string id)
        {
            if (IsExists(id))
            {
                WC_MessageResponse entity = m_Rep.GetById(id);
                WC_MessageResponseModel model = new WC_MessageResponseModel();
                              				model.Id = entity.Id;
				model.OfficalAccountId = entity.OfficalAccountId;
				model.MessageRule = entity.MessageRule;
				model.Category = entity.Category;
				model.MatchKey = entity.MatchKey;
				model.TextContent = entity.TextContent;
				model.ImgTextContext = entity.ImgTextContext;
				model.ImgTextUrl = entity.ImgTextUrl;
				model.ImgTextLink = entity.ImgTextLink;
				model.MeidaUrl = entity.MeidaUrl;
				model.MeidaLink = entity.MeidaLink;
				model.Enable = entity.Enable;
				model.IsDefault = entity.IsDefault;
				model.Remark = entity.Remark;
				model.Sort = entity.Sort;
				model.CreateTime = entity.CreateTime;
				model.CreateBy = entity.CreateBy;
				model.ModifyTime = entity.ModifyTime;
				model.ModifyBy = entity.ModifyBy;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
