//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.WC.IDAL;
using Apps.Models.WC;
namespace Apps.WC.BLL
{
	public class Virtual_WC_ResponseLogBLL
	{
        [Dependency]
        public IWC_ResponseLogRepository m_Rep { get; set; }

		public virtual List<WC_ResponseLogModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<WC_ResponseLog> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.OfficalAccountId.Contains(queryStr)
								|| a.OpenId.Contains(queryStr)
								
								|| a.RequestContent.Contains(queryStr)
								
								|| a.ResponseContent.Contains(queryStr)
								
								|| a.CreateBy.Contains(queryStr)
								
								|| a.ModifyBy.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<WC_ResponseLogModel> CreateModelList(ref IQueryable<WC_ResponseLog> queryData)
        {

            List<WC_ResponseLogModel> modelList = (from r in queryData
                                              select new WC_ResponseLogModel
                                              {
													Id = r.Id,
													OfficalAccountId = r.OfficalAccountId,
													OpenId = r.OpenId,
													RequestType = r.RequestType,
													RequestContent = r.RequestContent,
													ResponseType = r.ResponseType,
													ResponseContent = r.ResponseContent,
													CreateTime = r.CreateTime,
													CreateBy = r.CreateBy,
													ModifyTime = r.ModifyTime,
													ModifyBy = r.ModifyBy,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, WC_ResponseLogModel model)
        {
            try
            {
			    WC_ResponseLog entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new WC_ResponseLog(); 
				entity.Id = model.Id;
				entity.OfficalAccountId = model.OfficalAccountId;
				entity.OpenId = model.OpenId;
				entity.RequestType = model.RequestType;
				entity.RequestContent = model.RequestContent;
				entity.ResponseType = model.ResponseType;
				entity.ResponseContent = model.ResponseContent;
				entity.CreateTime = model.CreateTime;
				entity.CreateBy = model.CreateBy;
				entity.ModifyTime = model.ModifyTime;
				entity.ModifyBy = model.ModifyBy;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, WC_ResponseLogModel model)
        {
            try
            {
                WC_ResponseLog entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.OfficalAccountId = model.OfficalAccountId;
				entity.OpenId = model.OpenId;
				entity.RequestType = model.RequestType;
				entity.RequestContent = model.RequestContent;
				entity.ResponseType = model.ResponseType;
				entity.ResponseContent = model.ResponseContent;
				entity.CreateTime = model.CreateTime;
				entity.CreateBy = model.CreateBy;
				entity.ModifyTime = model.ModifyTime;
				entity.ModifyBy = model.ModifyBy;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual WC_ResponseLogModel GetById(string id)
        {
            if (IsExists(id))
            {
                WC_ResponseLog entity = m_Rep.GetById(id);
                WC_ResponseLogModel model = new WC_ResponseLogModel();
                              				model.Id = entity.Id;
				model.OfficalAccountId = entity.OfficalAccountId;
				model.OpenId = entity.OpenId;
				model.RequestType = entity.RequestType;
				model.RequestContent = entity.RequestContent;
				model.ResponseType = entity.ResponseType;
				model.ResponseContent = entity.ResponseContent;
				model.CreateTime = entity.CreateTime;
				model.CreateBy = entity.CreateBy;
				model.ModifyTime = entity.ModifyTime;
				model.ModifyBy = entity.ModifyBy;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
