//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.WC.IDAL;
using Apps.Models.WC;
namespace Apps.WC.BLL
{
	public class Virtual_WC_UserBLL
	{
        [Dependency]
        public IWC_UserRepository m_Rep { get; set; }

		public virtual List<WC_UserModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<WC_User> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.OpenId.Contains(queryStr)
								|| a.NickName.Contains(queryStr)
								
								|| a.Language.Contains(queryStr)
								|| a.City.Contains(queryStr)
								|| a.Province.Contains(queryStr)
								|| a.Country.Contains(queryStr)
								|| a.HeadImgUrl.Contains(queryStr)
								
								|| a.UnionId.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								|| a.GroupId.Contains(queryStr)
								|| a.TagidList.Contains(queryStr)
								
								|| a.OfficalAccountId.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<WC_UserModel> CreateModelList(ref IQueryable<WC_User> queryData)
        {

            List<WC_UserModel> modelList = (from r in queryData
                                              select new WC_UserModel
                                              {
													Id = r.Id,
													OpenId = r.OpenId,
													NickName = r.NickName,
													Sex = r.Sex,
													Language = r.Language,
													City = r.City,
													Province = r.Province,
													Country = r.Country,
													HeadImgUrl = r.HeadImgUrl,
													SubscribeTime = r.SubscribeTime,
													UnionId = r.UnionId,
													Remark = r.Remark,
													GroupId = r.GroupId,
													TagidList = r.TagidList,
													Subscribe = r.Subscribe,
													OfficalAccountId = r.OfficalAccountId,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, WC_UserModel model)
        {
            try
            {
			    WC_User entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new WC_User(); 
				entity.Id = model.Id;
				entity.OpenId = model.OpenId;
				entity.NickName = model.NickName;
				entity.Sex = model.Sex;
				entity.Language = model.Language;
				entity.City = model.City;
				entity.Province = model.Province;
				entity.Country = model.Country;
				entity.HeadImgUrl = model.HeadImgUrl;
				entity.SubscribeTime = model.SubscribeTime;
				entity.UnionId = model.UnionId;
				entity.Remark = model.Remark;
				entity.GroupId = model.GroupId;
				entity.TagidList = model.TagidList;
				entity.Subscribe = model.Subscribe;
				entity.OfficalAccountId = model.OfficalAccountId;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, WC_UserModel model)
        {
            try
            {
                WC_User entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.OpenId = model.OpenId;
				entity.NickName = model.NickName;
				entity.Sex = model.Sex;
				entity.Language = model.Language;
				entity.City = model.City;
				entity.Province = model.Province;
				entity.Country = model.Country;
				entity.HeadImgUrl = model.HeadImgUrl;
				entity.SubscribeTime = model.SubscribeTime;
				entity.UnionId = model.UnionId;
				entity.Remark = model.Remark;
				entity.GroupId = model.GroupId;
				entity.TagidList = model.TagidList;
				entity.Subscribe = model.Subscribe;
				entity.OfficalAccountId = model.OfficalAccountId;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual WC_UserModel GetById(string id)
        {
            if (IsExists(id))
            {
                WC_User entity = m_Rep.GetById(id);
                WC_UserModel model = new WC_UserModel();
                              				model.Id = entity.Id;
				model.OpenId = entity.OpenId;
				model.NickName = entity.NickName;
				model.Sex = entity.Sex;
				model.Language = entity.Language;
				model.City = entity.City;
				model.Province = entity.Province;
				model.Country = entity.Country;
				model.HeadImgUrl = entity.HeadImgUrl;
				model.SubscribeTime = entity.SubscribeTime;
				model.UnionId = entity.UnionId;
				model.Remark = entity.Remark;
				model.GroupId = entity.GroupId;
				model.TagidList = entity.TagidList;
				model.Subscribe = entity.Subscribe;
				model.OfficalAccountId = entity.OfficalAccountId;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
