//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.WC.IDAL;
using Apps.Models.WC;
namespace Apps.WC.BLL
{
	public class Virtual_WC_OfficalAccountsBLL
	{
        [Dependency]
        public IWC_OfficalAccountsRepository m_Rep { get; set; }

		public virtual List<WC_OfficalAccountsModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<WC_OfficalAccounts> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.OfficalId.Contains(queryStr)
								|| a.OfficalName.Contains(queryStr)
								|| a.OfficalCode.Contains(queryStr)
								|| a.OfficalPhoto.Contains(queryStr)
								|| a.OfficalKey.Contains(queryStr)
								|| a.ApiUrl.Contains(queryStr)
								|| a.Token.Contains(queryStr)
								|| a.AppId.Contains(queryStr)
								|| a.AppSecret.Contains(queryStr)
								|| a.AccessToken.Contains(queryStr)
								|| a.Remark.Contains(queryStr)
								
								
								
								
								|| a.CreateBy.Contains(queryStr)
								
								|| a.ModifyBy.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<WC_OfficalAccountsModel> CreateModelList(ref IQueryable<WC_OfficalAccounts> queryData)
        {

            List<WC_OfficalAccountsModel> modelList = (from r in queryData
                                              select new WC_OfficalAccountsModel
                                              {
													Id = r.Id,
													OfficalId = r.OfficalId,
													OfficalName = r.OfficalName,
													OfficalCode = r.OfficalCode,
													OfficalPhoto = r.OfficalPhoto,
													OfficalKey = r.OfficalKey,
													ApiUrl = r.ApiUrl,
													Token = r.Token,
													AppId = r.AppId,
													AppSecret = r.AppSecret,
													AccessToken = r.AccessToken,
													Remark = r.Remark,
													Enable = r.Enable,
													IsDefault = r.IsDefault,
													Category = r.Category,
													CreateTime = r.CreateTime,
													CreateBy = r.CreateBy,
													ModifyTime = r.ModifyTime,
													ModifyBy = r.ModifyBy,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, WC_OfficalAccountsModel model)
        {
            try
            {
			    WC_OfficalAccounts entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new WC_OfficalAccounts(); 
				entity.Id = model.Id;
				entity.OfficalId = model.OfficalId;
				entity.OfficalName = model.OfficalName;
				entity.OfficalCode = model.OfficalCode;
				entity.OfficalPhoto = model.OfficalPhoto;
				entity.OfficalKey = model.OfficalKey;
				entity.ApiUrl = model.ApiUrl;
				entity.Token = model.Token;
				entity.AppId = model.AppId;
				entity.AppSecret = model.AppSecret;
				entity.AccessToken = model.AccessToken;
				entity.Remark = model.Remark;
				entity.Enable = model.Enable;
				entity.IsDefault = model.IsDefault;
				entity.Category = model.Category;
				entity.CreateTime = model.CreateTime;
				entity.CreateBy = model.CreateBy;
				entity.ModifyTime = model.ModifyTime;
				entity.ModifyBy = model.ModifyBy;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, WC_OfficalAccountsModel model)
        {
            try
            {
                WC_OfficalAccounts entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.OfficalId = model.OfficalId;
				entity.OfficalName = model.OfficalName;
				entity.OfficalCode = model.OfficalCode;
				entity.OfficalPhoto = model.OfficalPhoto;
				entity.OfficalKey = model.OfficalKey;
				entity.ApiUrl = model.ApiUrl;
				entity.Token = model.Token;
				entity.AppId = model.AppId;
				entity.AppSecret = model.AppSecret;
				entity.AccessToken = model.AccessToken;
				entity.Remark = model.Remark;
				entity.Enable = model.Enable;
				entity.IsDefault = model.IsDefault;
				entity.Category = model.Category;
				entity.CreateTime = model.CreateTime;
				entity.CreateBy = model.CreateBy;
				entity.ModifyTime = model.ModifyTime;
				entity.ModifyBy = model.ModifyBy;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual WC_OfficalAccountsModel GetById(string id)
        {
            if (IsExists(id))
            {
                WC_OfficalAccounts entity = m_Rep.GetById(id);
                WC_OfficalAccountsModel model = new WC_OfficalAccountsModel();
                              				model.Id = entity.Id;
				model.OfficalId = entity.OfficalId;
				model.OfficalName = entity.OfficalName;
				model.OfficalCode = entity.OfficalCode;
				model.OfficalPhoto = entity.OfficalPhoto;
				model.OfficalKey = entity.OfficalKey;
				model.ApiUrl = entity.ApiUrl;
				model.Token = entity.Token;
				model.AppId = entity.AppId;
				model.AppSecret = entity.AppSecret;
				model.AccessToken = entity.AccessToken;
				model.Remark = entity.Remark;
				model.Enable = entity.Enable;
				model.IsDefault = entity.IsDefault;
				model.Category = entity.Category;
				model.CreateTime = entity.CreateTime;
				model.CreateBy = entity.CreateBy;
				model.ModifyTime = entity.ModifyTime;
				model.ModifyBy = entity.ModifyBy;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
