//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.WC.IBLL;
namespace Apps.WC.BLL
{
	public partial class WC_UserBLL: Virtual_WC_UserBLL,IWC_UserBLL
	{
        

	}
}
