//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2012-12-07 20:55:35 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Practices.Unity;
using Apps.Models;
using Apps.Common;
using Apps.BLL.Core;
using System.Transactions;
using Apps.IDAL;
using Apps.IBLL;
using Apps.Models.Sys;
using Apps.Locale;

namespace Apps.BLL
{
    public partial class SysUserConfigBLL
    {

        public SysUserConfigModel GetById(string id, string userId)
        {

            SysUserConfig entity = m_Rep.GetById(id, userId);
            if (entity == null)
            {
                return null;
            }
            SysUserConfigModel model = new SysUserConfigModel();
            model.Id = entity.Id;
            model.Name = entity.Name;
            model.Value = entity.Value;
            model.Type = entity.Type;
            model.State = entity.State;
            model.UserId = entity.UserId;
            return model;

        }
    }
}
