//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    using Apps.Common;
    
    public partial class DBContainer : DbContext
    {
        public DBContainer()
            : base(ConfigPara.EFDBConnection)
            //: base("name=DBContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DEF_CaseType> DEF_CaseType { get; set; }
        public virtual DbSet<DEF_Defect> DEF_Defect { get; set; }
        public virtual DbSet<DEF_TestCase> DEF_TestCase { get; set; }
        public virtual DbSet<DEF_TestCaseRelation> DEF_TestCaseRelation { get; set; }
        public virtual DbSet<DEF_TestCaseSteps> DEF_TestCaseSteps { get; set; }
        public virtual DbSet<DEF_TestJobs> DEF_TestJobs { get; set; }
        public virtual DbSet<DEF_TestJobsDetail> DEF_TestJobsDetail { get; set; }
        public virtual DbSet<DEF_TestJobsDetailItem> DEF_TestJobsDetailItem { get; set; }
        public virtual DbSet<DEF_TestJobsDetailRelation> DEF_TestJobsDetailRelation { get; set; }
        public virtual DbSet<DEF_TestJobsDetailSteps> DEF_TestJobsDetailSteps { get; set; }
        public virtual DbSet<SysAreas> SysAreas { get; set; }
        public virtual DbSet<SysException> SysException { get; set; }
        public virtual DbSet<SysLog> SysLog { get; set; }
        public virtual DbSet<SysModule> SysModule { get; set; }
        public virtual DbSet<SysModuleOperate> SysModuleOperate { get; set; }
        public virtual DbSet<SysPosition> SysPosition { get; set; }
        public virtual DbSet<SysRight> SysRight { get; set; }
        public virtual DbSet<SysRightOperate> SysRightOperate { get; set; }
        public virtual DbSet<SysRole> SysRole { get; set; }
        public virtual DbSet<SysSample> SysSample { get; set; }
        public virtual DbSet<SysSettings> SysSettings { get; set; }
        public virtual DbSet<SysStruct> SysStruct { get; set; }
        public virtual DbSet<SysUserConfig> SysUserConfig { get; set; }
        public virtual DbSet<V_DEF_Defect> V_DEF_Defect { get; set; }
        public virtual DbSet<V_DEF_RPT_DefectReport> V_DEF_RPT_DefectReport { get; set; }
        public virtual DbSet<SysUser> SysUser { get; set; }
        public virtual DbSet<MIS_Article> MIS_Article { get; set; }
        public virtual DbSet<MIS_Article_Albums> MIS_Article_Albums { get; set; }
        public virtual DbSet<MIS_Article_Category> MIS_Article_Category { get; set; }
        public virtual DbSet<MIS_Article_Comment> MIS_Article_Comment { get; set; }
        public virtual DbSet<MIS_WebIM_CommonTalk> MIS_WebIM_CommonTalk { get; set; }
        public virtual DbSet<MIS_WebIM_Message> MIS_WebIM_Message { get; set; }
        public virtual DbSet<MIS_WebIM_Message_Rec> MIS_WebIM_Message_Rec { get; set; }
        public virtual DbSet<MIS_WebIM_RecentContact> MIS_WebIM_RecentContact { get; set; }
        public virtual DbSet<Flow_Form> Flow_Form { get; set; }
        public virtual DbSet<Flow_FormAttr> Flow_FormAttr { get; set; }
        public virtual DbSet<Flow_FormContent> Flow_FormContent { get; set; }
        public virtual DbSet<Flow_FormContentStepCheck> Flow_FormContentStepCheck { get; set; }
        public virtual DbSet<Flow_FormContentStepCheckState> Flow_FormContentStepCheckState { get; set; }
        public virtual DbSet<Flow_Seal> Flow_Seal { get; set; }
        public virtual DbSet<Flow_Step> Flow_Step { get; set; }
        public virtual DbSet<Flow_StepRule> Flow_StepRule { get; set; }
        public virtual DbSet<Flow_Type> Flow_Type { get; set; }
        public virtual DbSet<JOB_TASKJOBS> JOB_TASKJOBS { get; set; }
        public virtual DbSet<JOB_TASKJOBS_LOG> JOB_TASKJOBS_LOG { get; set; }
        public virtual DbSet<Spl_Product> Spl_Product { get; set; }
        public virtual DbSet<Spl_ProductCategory> Spl_ProductCategory { get; set; }
        public virtual DbSet<Spl_Person> Spl_Person { get; set; }
        public virtual DbSet<WC_MessageResponse> WC_MessageResponse { get; set; }
        public virtual DbSet<WC_OfficalAccounts> WC_OfficalAccounts { get; set; }
        public virtual DbSet<WC_ResponseLog> WC_ResponseLog { get; set; }
        public virtual DbSet<WC_Group> WC_Group { get; set; }
        public virtual DbSet<WC_User> WC_User { get; set; }
    
        public virtual int P_DEF_CreateTestJobs(string vercode)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_CreateTestJobs", vercodeParameter);
        }
    
        public virtual int P_DEF_CopyTestJobs(string vercode, string newvercode)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var newvercodeParameter = newvercode != null ?
                new ObjectParameter("newvercode", newvercode) :
                new ObjectParameter("newvercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_CopyTestJobs", vercodeParameter, newvercodeParameter);
        }
    
        public virtual int P_DEF_CreateDefectReport(string vercode, string creator)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var creatorParameter = creator != null ?
                new ObjectParameter("creator", creator) :
                new ObjectParameter("creator", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_CreateDefectReport", vercodeParameter, creatorParameter);
        }
    
        public virtual int P_DEF_CreateTestJobsDetailRelation(string vercode)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_CreateTestJobsDetailRelation", vercodeParameter);
        }
    
        public virtual int P_DEF_CreateTestJobsDetailRelationByCode(string vercode, string code)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_CreateTestJobsDetailRelationByCode", vercodeParameter, codeParameter);
        }
    
        public virtual int P_DEF_CreateTestJobsItem(string vercode, string code)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_CreateTestJobsItem", vercodeParameter, codeParameter);
        }
    
        public virtual ObjectResult<P_DEF_CreateTestType_Result> P_DEF_CreateTestType()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_DEF_CreateTestType_Result>("P_DEF_CreateTestType");
        }
    
        public virtual int P_DEF_DeleteTestJobs(string vercode)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_DeleteTestJobs", vercodeParameter);
        }
    
        public virtual int P_DEF_DeleteTestJobsDetail(string vercode, string code)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_DeleteTestJobsDetail", vercodeParameter, codeParameter);
        }
    
        public virtual int P_DEF_DeleteTestJobsItem(string vercode, string code)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_DeleteTestJobsItem", vercodeParameter, codeParameter);
        }
    
        public virtual int P_DEF_DEV_UpdateState(string vercode, string code)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_DEV_UpdateState", vercodeParameter, codeParameter);
        }
    
        public virtual ObjectResult<V_DEF_Defect> P_DEF_QueryDefect(string queryType, Nullable<int> pageno, Nullable<int> rows, string order, ObjectParameter rowscount)
        {
            var queryTypeParameter = queryType != null ?
                new ObjectParameter("queryType", queryType) :
                new ObjectParameter("queryType", typeof(string));
    
            var pagenoParameter = pageno.HasValue ?
                new ObjectParameter("pageno", pageno) :
                new ObjectParameter("pageno", typeof(int));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("rows", rows) :
                new ObjectParameter("rows", typeof(int));
    
            var orderParameter = order != null ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<V_DEF_Defect>("P_DEF_QueryDefect", queryTypeParameter, pagenoParameter, rowsParameter, orderParameter, rowscount);
        }
    
        public virtual ObjectResult<V_DEF_Defect> P_DEF_QueryDefect(string queryType, Nullable<int> pageno, Nullable<int> rows, string order, ObjectParameter rowscount, MergeOption mergeOption)
        {
            var queryTypeParameter = queryType != null ?
                new ObjectParameter("queryType", queryType) :
                new ObjectParameter("queryType", typeof(string));
    
            var pagenoParameter = pageno.HasValue ?
                new ObjectParameter("pageno", pageno) :
                new ObjectParameter("pageno", typeof(int));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("rows", rows) :
                new ObjectParameter("rows", typeof(int));
    
            var orderParameter = order != null ?
                new ObjectParameter("order", order) :
                new ObjectParameter("order", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<V_DEF_Defect>("P_DEF_QueryDefect", mergeOption, queryTypeParameter, pagenoParameter, rowsParameter, orderParameter, rowscount);
        }
    
        public virtual ObjectResult<P_DEF_QueryDefectReport_Result> P_DEF_QueryDefectReport(string vercode)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_DEF_QueryDefectReport_Result>("P_DEF_QueryDefectReport", vercodeParameter);
        }
    
        public virtual int P_DEF_QueryDefectReportByCode(string vercode, string code)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            var codeParameter = code != null ?
                new ObjectParameter("code", code) :
                new ObjectParameter("code", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_QueryDefectReportByCode", vercodeParameter, codeParameter);
        }
    
        public virtual ObjectResult<P_DEF_REP_DefectReport_Result> P_DEF_REP_DefectReport(string vercode)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_DEF_REP_DefectReport_Result>("P_DEF_REP_DefectReport", vercodeParameter);
        }
    
        public virtual int P_DEF_SetTestJobsDefault(string vercode)
        {
            var vercodeParameter = vercode != null ?
                new ObjectParameter("vercode", vercode) :
                new ObjectParameter("vercode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_DEF_SetTestJobsDefault", vercodeParameter);
        }
    
        public virtual int P_JOB_DeleteTaskJobs(string sno)
        {
            var snoParameter = sno != null ?
                new ObjectParameter("sno", sno) :
                new ObjectParameter("sno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_JOB_DeleteTaskJobs", snoParameter);
        }
    
        public virtual int P_JOB_ENTERY(string sno)
        {
            var snoParameter = sno != null ?
                new ObjectParameter("sno", sno) :
                new ObjectParameter("sno", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_JOB_ENTERY", snoParameter);
        }
    
        public virtual ObjectResult<P_JOB_GetUnTrackTask_Result> P_JOB_GetUnTrackTask()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_JOB_GetUnTrackTask_Result>("P_JOB_GetUnTrackTask");
        }
    
        public virtual int P_JOB_U1(string cUSTOMERID)
        {
            var cUSTOMERIDParameter = cUSTOMERID != null ?
                new ObjectParameter("CUSTOMERID", cUSTOMERID) :
                new ObjectParameter("CUSTOMERID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_JOB_U1", cUSTOMERIDParameter);
        }
    
        public virtual int P_JOB_UpdateState(string sno, Nullable<int> state, string result)
        {
            var snoParameter = sno != null ?
                new ObjectParameter("sno", sno) :
                new ObjectParameter("sno", typeof(string));
    
            var stateParameter = state.HasValue ?
                new ObjectParameter("state", state) :
                new ObjectParameter("state", typeof(int));
    
            var resultParameter = result != null ?
                new ObjectParameter("result", result) :
                new ObjectParameter("result", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_JOB_UpdateState", snoParameter, stateParameter, resultParameter);
        }
    
        public virtual ObjectResult<P_QRTZ_GetJobExecuteTime_Result> P_QRTZ_GetJobExecuteTime(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_QRTZ_GetJobExecuteTime_Result>("P_QRTZ_GetJobExecuteTime", idParameter);
        }
    
        public virtual int P_Sys_ClearUnusedRightOperate()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_ClearUnusedRightOperate");
        }
    
        public virtual int P_Sys_DeleteSysRoleSysUserByRoleId(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_DeleteSysRoleSysUserByRoleId", roleIdParameter);
        }
    
        public virtual int P_Sys_DeleteSysRoleSysUserByUserId(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_DeleteSysRoleSysUserByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetModule_RoleRight_Result> P_Sys_GetModule_RoleRight(string moduleId)
        {
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("moduleId", moduleId) :
                new ObjectParameter("moduleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetModule_RoleRight_Result>("P_Sys_GetModule_RoleRight", moduleIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetModule_UserRight_Result> P_Sys_GetModule_UserRight(string moduleId)
        {
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("moduleId", moduleId) :
                new ObjectParameter("moduleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetModule_UserRight_Result>("P_Sys_GetModule_UserRight", moduleIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRightByRole_Result> P_Sys_GetRightByRole(string roleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRightByRole_Result>("P_Sys_GetRightByRole", roleIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRightByRoleAndModule_Result> P_Sys_GetRightByRoleAndModule(string roleId, string moduleId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("moduleId", moduleId) :
                new ObjectParameter("moduleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRightByRoleAndModule_Result>("P_Sys_GetRightByRoleAndModule", roleIdParameter, moduleIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRightByUser_Result> P_Sys_GetRightByUser(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRightByUser_Result>("P_Sys_GetRightByUser", userIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRightOperate_Result> P_Sys_GetRightOperate(string userId, string url)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            var urlParameter = url != null ?
                new ObjectParameter("url", url) :
                new ObjectParameter("url", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRightOperate_Result>("P_Sys_GetRightOperate", userIdParameter, urlParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetRoleByUserId_Result> P_Sys_GetRoleByUserId(string userId)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetRoleByUserId_Result>("P_Sys_GetRoleByUserId", userIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetUserByDepId_Result> P_Sys_GetUserByDepId(string depId)
        {
            var depIdParameter = depId != null ?
                new ObjectParameter("DepId", depId) :
                new ObjectParameter("DepId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetUserByDepId_Result>("P_Sys_GetUserByDepId", depIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetUserByRoleId_Result> P_Sys_GetUserByRoleId(string roleId, string depId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("RoleId", roleId) :
                new ObjectParameter("RoleId", typeof(string));
    
            var depIdParameter = depId != null ?
                new ObjectParameter("DepId", depId) :
                new ObjectParameter("DepId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetUserByRoleId_Result>("P_Sys_GetUserByRoleId", roleIdParameter, depIdParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> P_Sys_GetUserCountByDepId(string depId)
        {
            var depIdParameter = depId != null ?
                new ObjectParameter("DepId", depId) :
                new ObjectParameter("DepId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("P_Sys_GetUserCountByDepId", depIdParameter);
        }
    
        public virtual int P_Sys_InsertSysRight()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_InsertSysRight");
        }
    
        public virtual int P_Sys_UpdateSysRightRightFlag(string moduleId, string roleId)
        {
            var moduleIdParameter = moduleId != null ?
                new ObjectParameter("moduleId", moduleId) :
                new ObjectParameter("moduleId", typeof(string));
    
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_UpdateSysRightRightFlag", moduleIdParameter, roleIdParameter);
        }
    
        public virtual int P_Sys_UpdateSysRoleSysUser(string roleId, string userId)
        {
            var roleIdParameter = roleId != null ?
                new ObjectParameter("roleId", roleId) :
                new ObjectParameter("roleId", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Sys_UpdateSysRoleSysUser", roleIdParameter, userIdParameter);
        }
    
        public virtual ObjectResult<P_Sys_WebPart_Result> P_WebPart_GetInfo(Nullable<int> rows, string userId)
        {
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("Rows", rows) :
                new ObjectParameter("Rows", typeof(int));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_WebPart_Result>("P_WebPart_GetInfo", rowsParameter, userIdParameter);
        }
    
        public virtual int P_MIS_CreateMessage(string id, string message, string sender, string receiver, string receiverTitle)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var messageParameter = message != null ?
                new ObjectParameter("message", message) :
                new ObjectParameter("message", typeof(string));
    
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            var receiverTitleParameter = receiverTitle != null ?
                new ObjectParameter("receiverTitle", receiverTitle) :
                new ObjectParameter("receiverTitle", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_CreateMessage", idParameter, messageParameter, senderParameter, receiverParameter, receiverTitleParameter);
        }
    
        public virtual int P_MIS_DeleteMessageAllByReceiver(string receiver)
        {
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_DeleteMessageAllByReceiver", receiverParameter);
        }
    
        public virtual int P_MIS_DeleteMessageAllBySender(string sender)
        {
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_DeleteMessageAllBySender", senderParameter);
        }
    
        public virtual int P_MIS_DeleteMessageByReceiver(string id, string receiver)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_DeleteMessageByReceiver", idParameter, receiverParameter);
        }
    
        public virtual int P_MIS_DeleteMessageBySender(string id)
        {
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_DeleteMessageBySender", idParameter);
        }
    
        public virtual ObjectResult<MIS_WebIM_Message> P_MIS_GetMessage(string user, Nullable<int> pageno, Nullable<int> rows, ObjectParameter rowscount)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var pagenoParameter = pageno.HasValue ?
                new ObjectParameter("pageno", pageno) :
                new ObjectParameter("pageno", typeof(int));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("rows", rows) :
                new ObjectParameter("rows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIS_WebIM_Message>("P_MIS_GetMessage", userParameter, pagenoParameter, rowsParameter, rowscount);
        }
    
        public virtual ObjectResult<MIS_WebIM_Message> P_MIS_GetMessage(string user, Nullable<int> pageno, Nullable<int> rows, ObjectParameter rowscount, MergeOption mergeOption)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var pagenoParameter = pageno.HasValue ?
                new ObjectParameter("pageno", pageno) :
                new ObjectParameter("pageno", typeof(int));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("rows", rows) :
                new ObjectParameter("rows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<MIS_WebIM_Message>("P_MIS_GetMessage", mergeOption, userParameter, pagenoParameter, rowsParameter, rowscount);
        }
    
        public virtual ObjectResult<P_MIS_GetSenderByReceiver_Result> P_MIS_GetSenderByReceiver(string receiver)
        {
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_MIS_GetSenderByReceiver_Result>("P_MIS_GetSenderByReceiver", receiverParameter);
        }
    
        public virtual int P_MIS_Info_EduMessage(Nullable<int> id, string infoId, string body, string userId)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var infoIdParameter = infoId != null ?
                new ObjectParameter("InfoId", infoId) :
                new ObjectParameter("InfoId", typeof(string));
    
            var bodyParameter = body != null ?
                new ObjectParameter("Body", body) :
                new ObjectParameter("Body", typeof(string));
    
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_Info_EduMessage", idParameter, infoIdParameter, bodyParameter, userIdParameter);
        }
    
        public virtual int P_MIS_Info_GetFavoriteByUserId(string userId, string whereSQL)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var whereSQLParameter = whereSQL != null ?
                new ObjectParameter("WhereSQL", whereSQL) :
                new ObjectParameter("WhereSQL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_Info_GetFavoriteByUserId", userIdParameter, whereSQLParameter);
        }
    
        public virtual int P_MIS_Info_GetICanManage(string whereSQL, Nullable<int> rows, Nullable<int> pageNo, ObjectParameter rowsCount)
        {
            var whereSQLParameter = whereSQL != null ?
                new ObjectParameter("WhereSQL", whereSQL) :
                new ObjectParameter("WhereSQL", typeof(string));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("Rows", rows) :
                new ObjectParameter("Rows", typeof(int));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_Info_GetICanManage", whereSQLParameter, rowsParameter, pageNoParameter, rowsCount);
        }
    
        public virtual int P_MIS_Info_GetICanRead(string userId, string whereSQL, Nullable<int> rows, Nullable<int> pageNo, ObjectParameter rowsCount)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var whereSQLParameter = whereSQL != null ?
                new ObjectParameter("WhereSQL", whereSQL) :
                new ObjectParameter("WhereSQL", typeof(string));
    
            var rowsParameter = rows.HasValue ?
                new ObjectParameter("Rows", rows) :
                new ObjectParameter("Rows", typeof(int));
    
            var pageNoParameter = pageNo.HasValue ?
                new ObjectParameter("PageNo", pageNo) :
                new ObjectParameter("PageNo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_Info_GetICanRead", userIdParameter, whereSQLParameter, rowsParameter, pageNoParameter, rowsCount);
        }
    
        public virtual int P_MIS_Info_GetPostInfoByUserId(string userId, string whereSQL)
        {
            var userIdParameter = userId != null ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(string));
    
            var whereSQLParameter = whereSQL != null ?
                new ObjectParameter("WhereSQL", whereSQL) :
                new ObjectParameter("WhereSQL", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_Info_GetPostInfoByUserId", userIdParameter, whereSQLParameter);
        }
    
        public virtual int P_MIS_SetMessageHasReadById(string receiver, string id)
        {
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            var idParameter = id != null ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_SetMessageHasReadById", receiverParameter, idParameter);
        }
    
        public virtual int P_MIS_SetMessageHasReadByReceiver(string receiver)
        {
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_SetMessageHasReadByReceiver", receiverParameter);
        }
    
        public virtual int P_MIS_SetMessageHasReadFromSenderToReceiver(string sender, string receiver)
        {
            var senderParameter = sender != null ?
                new ObjectParameter("sender", sender) :
                new ObjectParameter("sender", typeof(string));
    
            var receiverParameter = receiver != null ?
                new ObjectParameter("receiver", receiver) :
                new ObjectParameter("receiver", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_MIS_SetMessageHasReadFromSenderToReceiver", senderParameter, receiverParameter);
        }
    
        public virtual int P_Flow_ResetCheckStepState(string stepCheckId, string contentId, Nullable<int> checkState, Nullable<int> checkFlag)
        {
            var stepCheckIdParameter = stepCheckId != null ?
                new ObjectParameter("stepCheckId", stepCheckId) :
                new ObjectParameter("stepCheckId", typeof(string));
    
            var contentIdParameter = contentId != null ?
                new ObjectParameter("ContentId", contentId) :
                new ObjectParameter("ContentId", typeof(string));
    
            var checkStateParameter = checkState.HasValue ?
                new ObjectParameter("CheckState", checkState) :
                new ObjectParameter("CheckState", typeof(int));
    
            var checkFlagParameter = checkFlag.HasValue ?
                new ObjectParameter("CheckFlag", checkFlag) :
                new ObjectParameter("CheckFlag", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_Flow_ResetCheckStepState", stepCheckIdParameter, contentIdParameter, checkStateParameter, checkFlagParameter);
        }
    
        public virtual ObjectResult<P_Sys_GetAllUsers_Result> P_Sys_GetAllUsers()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_Sys_GetAllUsers_Result>("P_Sys_GetAllUsers");
        }
    
        public virtual ObjectResult<P_WC_GetResponseContent_Result> P_WC_GetResponseContent(string officalAccountId, string matchKey)
        {
            var officalAccountIdParameter = officalAccountId != null ?
                new ObjectParameter("officalAccountId", officalAccountId) :
                new ObjectParameter("officalAccountId", typeof(string));
    
            var matchKeyParameter = matchKey != null ?
                new ObjectParameter("matchKey", matchKey) :
                new ObjectParameter("matchKey", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<P_WC_GetResponseContent_Result>("P_WC_GetResponseContent", officalAccountIdParameter, matchKeyParameter);
        }
    }
}
