//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TestJobsDetailRelation
    {
        public string VerCode { get; set; }
        public string PCode { get; set; }
        public string CCode { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> ExSort { get; set; }
    
        public virtual DEF_TestJobsDetail DEF_TestJobsDetail { get; set; }
    }
}
