//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TestCase
    {
        public DEF_TestCase()
        {
            this.DEF_TestCaseRelation = new HashSet<DEF_TestCaseRelation>();
            this.DEF_TestCaseSteps = new HashSet<DEF_TestCaseSteps>();
            this.DEF_TestJobsDetail = new HashSet<DEF_TestJobsDetail>();
            this.DEF_TestJobsDetailItem = new HashSet<DEF_TestJobsDetailItem>();
        }
    
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string ModuleId { get; set; }
        public Nullable<int> Sort { get; set; }
    
        public virtual ICollection<DEF_TestCaseRelation> DEF_TestCaseRelation { get; set; }
        public virtual ICollection<DEF_TestCaseSteps> DEF_TestCaseSteps { get; set; }
        public virtual ICollection<DEF_TestJobsDetail> DEF_TestJobsDetail { get; set; }
        public virtual ICollection<DEF_TestJobsDetailItem> DEF_TestJobsDetailItem { get; set; }
    }
}
