//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TestJobsDetailItem
    {
        public DEF_TestJobsDetailItem()
        {
            this.DEF_TestJobsDetailSteps = new HashSet<DEF_TestJobsDetailSteps>();
        }
    
        public string VerCode { get; set; }
        public string Code { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> ExSort { get; set; }
        public bool Lock { get; set; }
        public string Developer { get; set; }
        public string Tester { get; set; }
        public Nullable<System.DateTime> FinDt { get; set; }
        public Nullable<bool> TestRequestFlag { get; set; }
        public Nullable<bool> DevFinFlag { get; set; }
    
        public virtual DEF_TestCase DEF_TestCase { get; set; }
        public virtual ICollection<DEF_TestJobsDetailSteps> DEF_TestJobsDetailSteps { get; set; }
    }
}
