//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TestJobsDetailSteps
    {
        public string ItemID { get; set; }
        public string VerCode { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string TestContent { get; set; }
        public Nullable<bool> Result { get; set; }
        public Nullable<int> Sort { get; set; }
        public string ResultContent { get; set; }
        public Nullable<int> ExSort { get; set; }
        public int StepType { get; set; }
        public string Tester { get; set; }
        public Nullable<System.DateTime> TestDt { get; set; }
        public string Developer { get; set; }
        public Nullable<System.DateTime> PlanStartDt { get; set; }
        public Nullable<System.DateTime> PlanEndDt { get; set; }
        public Nullable<System.DateTime> FinDt { get; set; }
        public Nullable<bool> TestRequestFlag { get; set; }
        public Nullable<bool> DevFinFlag { get; set; }
    
        public virtual DEF_TestJobsDetailItem DEF_TestJobsDetailItem { get; set; }
    }
}
