//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Apps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEF_TestCaseSteps
    {
        public string ItemID { get; set; }
        public string Code { get; set; }
        public string Title { get; set; }
        public string TestContent { get; set; }
        public Nullable<bool> state { get; set; }
        public Nullable<int> sort { get; set; }
    
        public virtual DEF_TestCase DEF_TestCase { get; set; }
    }
}
