//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.MIS.IBLL;
namespace Apps.MIS.BLL
{
	public partial class MIS_WebIM_RecentContactBLL: Virtual_MIS_WebIM_RecentContactBLL,IMIS_WebIM_RecentContactBLL
	{
        

	}
}
