//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.MIS.IDAL;
using Apps.Models.MIS;
namespace Apps.MIS.BLL
{
	public class Virtual_MIS_WebIM_Message_RecBLL
	{
        [Dependency]
        public IMIS_WebIM_Message_RecRepository m_Rep { get; set; }

		public virtual List<MIS_WebIM_Message_RecModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<MIS_WebIM_Message_Rec> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.MessageId.Contains(queryStr)
								|| a.receiver.Contains(queryStr)
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<MIS_WebIM_Message_RecModel> CreateModelList(ref IQueryable<MIS_WebIM_Message_Rec> queryData)
        {

            List<MIS_WebIM_Message_RecModel> modelList = (from r in queryData
                                              select new MIS_WebIM_Message_RecModel
                                              {
													MessageId = r.MessageId,
													receiver = r.receiver,
													State = r.State,
													RecDt = r.RecDt,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, MIS_WebIM_Message_RecModel model)
        {
            try
            {
                MIS_WebIM_Message_Rec entity = m_Rep.GetById(model.MessageId);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new MIS_WebIM_Message_Rec();
               				entity.MessageId = model.MessageId;
				entity.receiver = model.receiver;
				entity.State = model.State;
				entity.RecDt = model.RecDt;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, MIS_WebIM_Message_RecModel model)
        {
            try
            {
                MIS_WebIM_Message_Rec entity = m_Rep.GetById(model.MessageId);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.MessageId = model.MessageId;
				entity.receiver = model.receiver;
				entity.State = model.State;
				entity.RecDt = model.RecDt;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual MIS_WebIM_Message_RecModel GetById(string id)
        {
            if (IsExists(id))
            {
                MIS_WebIM_Message_Rec entity = m_Rep.GetById(id);
                MIS_WebIM_Message_RecModel model = new MIS_WebIM_Message_RecModel();
                              				model.MessageId = entity.MessageId;
				model.receiver = entity.receiver;
				model.State = entity.State;
				model.RecDt = entity.RecDt;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
