//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.MIS.IDAL;
using Apps.Models.MIS;
namespace Apps.MIS.BLL
{
	public class Virtual_MIS_ArticleBLL
	{
        [Dependency]
        public IMIS_ArticleRepository m_Rep { get; set; }

		public virtual List<MIS_ArticleModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<MIS_Article> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								
								|| a.CategoryId.Contains(queryStr)
								|| a.Title.Contains(queryStr)
								|| a.ImgUrl.Contains(queryStr)
								|| a.BodyContent.Contains(queryStr)
								
								
								
								|| a.Checker.Contains(queryStr)
								
								|| a.Creater.Contains(queryStr)
								
								|| a.CustomLink.Contains(queryStr)
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<MIS_ArticleModel> CreateModelList(ref IQueryable<MIS_Article> queryData)
        {

            List<MIS_ArticleModel> modelList = (from r in queryData
                                              select new MIS_ArticleModel
                                              {
													Id = r.Id,
													ChannelId = r.ChannelId,
													CategoryId = r.CategoryId,
													Title = r.Title,
													ImgUrl = r.ImgUrl,
													BodyContent = r.BodyContent,
													Sort = r.Sort,
													Click = r.Click,
													CheckFlag = r.CheckFlag,
													Checker = r.Checker,
													CheckDateTime = r.CheckDateTime,
													Creater = r.Creater,
													CreateTime = r.CreateTime,
													CustomLink = r.CustomLink,
													IsType = r.IsType,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, MIS_ArticleModel model)
        {
            try
            {
                MIS_Article entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new MIS_Article();
               				entity.Id = model.Id;
				entity.ChannelId = model.ChannelId;
				entity.CategoryId = model.CategoryId;
				entity.Title = model.Title;
				entity.ImgUrl = model.ImgUrl;
				entity.BodyContent = model.BodyContent;
				entity.Sort = model.Sort;
				entity.Click = model.Click;
				entity.CheckFlag = model.CheckFlag;
				entity.Checker = model.Checker;
				entity.CheckDateTime = model.CheckDateTime;
				entity.Creater = model.Creater;
				entity.CreateTime = model.CreateTime;
				entity.CustomLink = model.CustomLink;
				entity.IsType = model.IsType;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, MIS_ArticleModel model)
        {
            try
            {
                MIS_Article entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.ChannelId = model.ChannelId;
				entity.CategoryId = model.CategoryId;
				entity.Title = model.Title;
				entity.ImgUrl = model.ImgUrl;
				entity.BodyContent = model.BodyContent;
				entity.Sort = model.Sort;
				entity.Click = model.Click;
				entity.CheckFlag = model.CheckFlag;
				entity.Checker = model.Checker;
				entity.CheckDateTime = model.CheckDateTime;
				entity.Creater = model.Creater;
				entity.CreateTime = model.CreateTime;
				entity.CustomLink = model.CustomLink;
				entity.IsType = model.IsType;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual MIS_ArticleModel GetById(string id)
        {
            if (IsExists(id))
            {
                MIS_Article entity = m_Rep.GetById(id);
                MIS_ArticleModel model = new MIS_ArticleModel();
                              				model.Id = entity.Id;
				model.ChannelId = entity.ChannelId;
				model.CategoryId = entity.CategoryId;
				model.Title = entity.Title;
				model.ImgUrl = entity.ImgUrl;
				model.BodyContent = entity.BodyContent;
				model.Sort = entity.Sort;
				model.Click = entity.Click;
				model.CheckFlag = entity.CheckFlag;
				model.Checker = entity.Checker;
				model.CheckDateTime = entity.CheckDateTime;
				model.Creater = entity.Creater;
				model.CreateTime = entity.CreateTime;
				model.CustomLink = entity.CustomLink;
				model.IsType = entity.IsType;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
