//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.MIS.IDAL;
using Apps.Models.MIS;
namespace Apps.MIS.BLL
{
	public class Virtual_MIS_WebIM_MessageBLL
	{
        [Dependency]
        public IMIS_WebIM_MessageRepository m_Rep { get; set; }

		public virtual List<MIS_WebIM_MessageModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<MIS_WebIM_Message> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Message.Contains(queryStr)
								|| a.Sender.Contains(queryStr)
								|| a.receiver.Contains(queryStr)
								
								
								|| a.receiverTitle.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<MIS_WebIM_MessageModel> CreateModelList(ref IQueryable<MIS_WebIM_Message> queryData)
        {

            List<MIS_WebIM_MessageModel> modelList = (from r in queryData
                                              select new MIS_WebIM_MessageModel
                                              {
													Id = r.Id,
													Message = r.Message,
													Sender = r.Sender,
													receiver = r.receiver,
													State = r.State,
													SendDt = r.SendDt,
													receiverTitle = r.receiverTitle,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, MIS_WebIM_MessageModel model)
        {
            try
            {
                MIS_WebIM_Message entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new MIS_WebIM_Message();
               				entity.Id = model.Id;
				entity.Message = model.Message;
				entity.Sender = model.Sender;
				entity.receiver = model.receiver;
				entity.State = model.State;
				entity.SendDt = model.SendDt;
				entity.receiverTitle = model.receiverTitle;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, MIS_WebIM_MessageModel model)
        {
            try
            {
                MIS_WebIM_Message entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.Message = model.Message;
				entity.Sender = model.Sender;
				entity.receiver = model.receiver;
				entity.State = model.State;
				entity.SendDt = model.SendDt;
				entity.receiverTitle = model.receiverTitle;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual MIS_WebIM_MessageModel GetById(string id)
        {
            if (IsExists(id))
            {
                MIS_WebIM_Message entity = m_Rep.GetById(id);
                MIS_WebIM_MessageModel model = new MIS_WebIM_MessageModel();
                              				model.Id = entity.Id;
				model.Message = entity.Message;
				model.Sender = entity.Sender;
				model.receiver = entity.receiver;
				model.State = entity.State;
				model.SendDt = entity.SendDt;
				model.receiverTitle = entity.receiverTitle;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
