//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Flow.IDAL;
using Apps.Models.Flow;
namespace Apps.Flow.BLL
{
	public class Virtual_Flow_FormContentStepCheckBLL
	{
        [Dependency]
        public IFlow_FormContentStepCheckRepository m_Rep { get; set; }

		public virtual List<Flow_FormContentStepCheckModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<Flow_FormContentStepCheck> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.ContentId.Contains(queryStr)
								|| a.StepId.Contains(queryStr)
								
								
								
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<Flow_FormContentStepCheckModel> CreateModelList(ref IQueryable<Flow_FormContentStepCheck> queryData)
        {

            List<Flow_FormContentStepCheckModel> modelList = (from r in queryData
                                              select new Flow_FormContentStepCheckModel
                                              {
													Id = r.Id,
													ContentId = r.ContentId,
													StepId = r.StepId,
													State = r.State,
													StateFlag = r.StateFlag,
													CreateTime = r.CreateTime,
													IsEnd = r.IsEnd,
													IsCustom = r.IsCustom,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, Flow_FormContentStepCheckModel model)
        {
            try
            {
			    Flow_FormContentStepCheck entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new Flow_FormContentStepCheck(); 
				entity.Id = model.Id;
				entity.ContentId = model.ContentId;
				entity.StepId = model.StepId;
				entity.State = model.State;
				entity.StateFlag = model.StateFlag;
				entity.CreateTime = model.CreateTime;
				entity.IsEnd = model.IsEnd;
				entity.IsCustom = model.IsCustom;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, Flow_FormContentStepCheckModel model)
        {
            try
            {
                Flow_FormContentStepCheck entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.ContentId = model.ContentId;
				entity.StepId = model.StepId;
				entity.State = model.State;
				entity.StateFlag = model.StateFlag;
				entity.CreateTime = model.CreateTime;
				entity.IsEnd = model.IsEnd;
				entity.IsCustom = model.IsCustom;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual Flow_FormContentStepCheckModel GetById(string id)
        {
            if (IsExists(id))
            {
                Flow_FormContentStepCheck entity = m_Rep.GetById(id);
                Flow_FormContentStepCheckModel model = new Flow_FormContentStepCheckModel();
                              				model.Id = entity.Id;
				model.ContentId = entity.ContentId;
				model.StepId = entity.StepId;
				model.State = entity.State;
				model.StateFlag = entity.StateFlag;
				model.CreateTime = entity.CreateTime;
				model.IsEnd = entity.IsEnd;
				model.IsCustom = entity.IsCustom;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
