//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由T4模板自动生成
//	   生成时间 2013-04-23 17:24:52 by App
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.Practices.Unity;
using Apps.Models;
using Apps.Common;
using Apps.BLL.Core;
using System.Transactions;
using Apps.Models.MIS;
using Apps.MIS.IBLL;
using Apps.MIS.IDAL;
using Apps.Locale;

namespace Apps.MIS.BLL
{
    public partial class MIS_Article_CommentBLL
    {
    }
}
