//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.DAL;
using Apps.DEF.IDAL;
using System;
namespace Apps.DEF.DAL
{
	public partial class DEF_TestJobsDetailRelationRepository:BaseRepository<DEF_TestJobsDetailRelation>,IDEF_TestJobsDetailRelationRepository,IDisposable
	{
	    public DEF_TestJobsDetailRelationRepository(DBContainer db):base(db)
        {
        
        }
     
	}
}
