//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using Apps.DAL;
using Apps.MIS.IDAL;
using System;
namespace Apps.MIS.DAL
{
	public partial class MIS_Article_AlbumsRepository:BaseRepository<MIS_Article_Albums>,IMIS_Article_AlbumsRepository,IDisposable
	{
	    public MIS_Article_AlbumsRepository(DBContainer db):base(db)
        {
        
        }
     
	}
}
