//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Sys
{
	public class Virtual_SysUserConfigModel
	{
			public virtual string Id { get; set; }
			public virtual string Name { get; set; }
			public virtual string Value { get; set; }
			public virtual string Type { get; set; }
			public virtual Nullable<bool> State { get; set; }
			public virtual string UserId { get; set; }
		}
}
