//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.V
{
	public class Virtual_V_DEF_RPT_DefectReportModel
	{
			public virtual string ItemID { get; set; }
			public virtual string Code { get; set; }
			public virtual string CodeTitle { get; set; }
			public virtual string Title { get; set; }
			public virtual Nullable<System.DateTime> CrtDt { get; set; }
			public virtual string Creator { get; set; }
			public virtual string CreatorTitle { get; set; }
			public virtual string VerCode { get; set; }
		}
}
