//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.JOB
{
	public class Virtual_JOB_TASKJOBSModel
	{
			public virtual string sno { get; set; }
			public virtual string taskName { get; set; }
			public virtual string Id { get; set; }
			public virtual string taskTitle { get; set; }
			public virtual string taskCmd { get; set; }
			public virtual Nullable<System.DateTime> crtDt { get; set; }
			public virtual Nullable<int> state { get; set; }
			public virtual string creator { get; set; }
			public virtual string procName { get; set; }
			public virtual string procParams { get; set; }
		}
}
