//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.MIS
{
	public class Virtual_MIS_Article_AlbumsModel
	{
			public virtual string Id { get; set; }
			public virtual string ArticleId { get; set; }
			public virtual string BigImg { get; set; }
			public virtual string SmallImg { get; set; }
			public virtual string Remark { get; set; }
		}
}
