//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Flow
{
	public class Virtual_Flow_StepModel
	{
			public virtual string Id { get; set; }
			public virtual string Name { get; set; }
			public virtual string Remark { get; set; }
			public virtual int Sort { get; set; }
			public virtual string FormId { get; set; }
			public virtual int FlowRule { get; set; }
			public virtual bool IsCustom { get; set; }
			public virtual bool IsAllCheck { get; set; }
			public virtual string Execution { get; set; }
			public virtual bool CompulsoryOver { get; set; }
			public virtual bool IsEditAttr { get; set; }
		}
}
