//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Flow
{
	public class Virtual_Flow_FormModel
	{
			public virtual string Id { get; set; }
			public virtual string Name { get; set; }
			public virtual string Remark { get; set; }
			public virtual string UsingDep { get; set; }
			public virtual string TypeId { get; set; }
			public virtual bool State { get; set; }
			public virtual Nullable<System.DateTime> CreateTime { get; set; }
			public virtual string HtmlForm { get; set; }
			public virtual string AttrA { get; set; }
			public virtual string AttrB { get; set; }
			public virtual string AttrC { get; set; }
			public virtual string AttrD { get; set; }
			public virtual string AttrE { get; set; }
			public virtual string AttrF { get; set; }
			public virtual string AttrG { get; set; }
			public virtual string AttrH { get; set; }
			public virtual string AttrI { get; set; }
			public virtual string AttrJ { get; set; }
			public virtual string AttrK { get; set; }
			public virtual string AttrL { get; set; }
			public virtual string AttrM { get; set; }
			public virtual string AttrN { get; set; }
			public virtual string AttrO { get; set; }
			public virtual string AttrP { get; set; }
			public virtual string AttrQ { get; set; }
			public virtual string AttrR { get; set; }
			public virtual string AttrS { get; set; }
			public virtual string AttrT { get; set; }
			public virtual string AttrU { get; set; }
			public virtual string AttrV { get; set; }
			public virtual string AttrW { get; set; }
			public virtual string AttrX { get; set; }
			public virtual string AttrY { get; set; }
			public virtual string AttrZ { get; set; }
		}
}
