//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Flow
{
	public class Virtual_Flow_FormContentStepCheckModel
	{
			public virtual string Id { get; set; }
			public virtual string ContentId { get; set; }
			public virtual string StepId { get; set; }
			public virtual int State { get; set; }
			public virtual bool StateFlag { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual bool IsEnd { get; set; }
			public virtual bool IsCustom { get; set; }
		}
}
