//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.DEF
{
	public class Virtual_DEF_TestCaseRelationModel
	{
			public virtual string PCode { get; set; }
			public virtual string CCode { get; set; }
			public virtual string ReMark { get; set; }
			public virtual Nullable<int> Sort { get; set; }
		}
}
