//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Flow
{
	public class Virtual_Flow_FormAttrModel
	{
			public virtual string Id { get; set; }
			public virtual string Title { get; set; }
			public virtual string Name { get; set; }
			public virtual string AttrType { get; set; }
			public virtual string CheckJS { get; set; }
			public virtual string TypeId { get; set; }
			public virtual Nullable<System.DateTime> CreateTime { get; set; }
			public virtual string OptionList { get; set; }
			public virtual Nullable<bool> IsValid { get; set; }
		}
}
