//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.WC
{
	public class Virtual_WC_GroupModel
	{
			public virtual string Id { get; set; }
			public virtual string Name { get; set; }
			public virtual int Count { get; set; }
			public virtual string OfficalAccountId { get; set; }
		}
}
