//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.MIS
{
	public class Virtual_MIS_ArticleModel
	{
			public virtual string Id { get; set; }
			public virtual int ChannelId { get; set; }
			public virtual string CategoryId { get; set; }
			public virtual string Title { get; set; }
			public virtual string ImgUrl { get; set; }
			public virtual string BodyContent { get; set; }
			public virtual Nullable<int> Sort { get; set; }
			public virtual Nullable<int> Click { get; set; }
			public virtual int CheckFlag { get; set; }
			public virtual string Checker { get; set; }
			public virtual Nullable<System.DateTime> CheckDateTime { get; set; }
			public virtual string Creater { get; set; }
			public virtual Nullable<System.DateTime> CreateTime { get; set; }
			public virtual string CustomLink { get; set; }
			public virtual int IsType { get; set; }
		}
}
