//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.WC
{
	public class Virtual_WC_OfficalAccountsModel
	{
			public virtual string Id { get; set; }
			public virtual string OfficalId { get; set; }
			public virtual string OfficalName { get; set; }
			public virtual string OfficalCode { get; set; }
			public virtual string OfficalPhoto { get; set; }
			public virtual string OfficalKey { get; set; }
			public virtual string ApiUrl { get; set; }
			public virtual string Token { get; set; }
			public virtual string AppId { get; set; }
			public virtual string AppSecret { get; set; }
			public virtual string AccessToken { get; set; }
			public virtual string Remark { get; set; }
			public virtual bool Enable { get; set; }
			public virtual bool IsDefault { get; set; }
			public virtual int Category { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual string CreateBy { get; set; }
			public virtual System.DateTime ModifyTime { get; set; }
			public virtual string ModifyBy { get; set; }
		}
}
