//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Spl
{
	public class Virtual_Spl_PersonModel
	{
			public virtual string Id { get; set; }
			public virtual string Name { get; set; }
			public virtual string Sex { get; set; }
			public virtual Nullable<int> Age { get; set; }
			public virtual string IDCard { get; set; }
			public virtual string Phone { get; set; }
			public virtual string Email { get; set; }
			public virtual string Address { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual string Region { get; set; }
			public virtual string Category { get; set; }
		}
}
