//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.Spl
{
	public class Virtual_Spl_ProductModel
	{
			public virtual string Id { get; set; }
			public virtual string Name { get; set; }
			public virtual string Code { get; set; }
			public virtual decimal Price { get; set; }
			public virtual string Color { get; set; }
			public virtual decimal Number { get; set; }
			public virtual string CategoryId { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual string CreateBy { get; set; }
			public virtual Nullable<decimal> CostPrice { get; set; }
		}
}
