//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.WC
{
	public class Virtual_WC_UserModel
	{
			public virtual string Id { get; set; }
			public virtual string OpenId { get; set; }
			public virtual string NickName { get; set; }
			public virtual int Sex { get; set; }
			public virtual string Language { get; set; }
			public virtual string City { get; set; }
			public virtual string Province { get; set; }
			public virtual string Country { get; set; }
			public virtual string HeadImgUrl { get; set; }
			public virtual System.DateTime SubscribeTime { get; set; }
			public virtual string UnionId { get; set; }
			public virtual string Remark { get; set; }
			public virtual string GroupId { get; set; }
			public virtual string TagidList { get; set; }
			public virtual int Subscribe { get; set; }
			public virtual string OfficalAccountId { get; set; }
		}
}
