//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.WC
{
	public class Virtual_WC_ResponseLogModel
	{
			public virtual string Id { get; set; }
			public virtual string OfficalAccountId { get; set; }
			public virtual string OpenId { get; set; }
			public virtual Nullable<int> RequestType { get; set; }
			public virtual string RequestContent { get; set; }
			public virtual Nullable<int> ResponseType { get; set; }
			public virtual string ResponseContent { get; set; }
			public virtual System.DateTime CreateTime { get; set; }
			public virtual string CreateBy { get; set; }
			public virtual System.DateTime ModifyTime { get; set; }
			public virtual string ModifyBy { get; set; }
		}
}
