//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.Models;
using System;
namespace Apps.Models.MIS
{
	public class Virtual_MIS_WebIM_RecentContactModel
	{
			public virtual int Id { get; set; }
			public virtual string ContactPersons { get; set; }
			public virtual string UserId { get; set; }
			public virtual System.DateTime InfoTime { get; set; }
			public virtual string ContactPersonsTitle { get; set; }
		}
}
