//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.Sys;
namespace Apps.BLL
{
	public class Virtual_SysModuleBLL
	{
        [Dependency]
        public ISysModuleRepository m_Rep { get; set; }

		public virtual List<SysModuleModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<SysModule> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.Id.Contains(queryStr)
								|| a.Name.Contains(queryStr)
								|| a.EnglishName.Contains(queryStr)
								|| a.ParentId.Contains(queryStr)
								|| a.Url.Contains(queryStr)
								|| a.Iconic.Contains(queryStr)
								
								|| a.Remark.Contains(queryStr)
								
								|| a.CreatePerson.Contains(queryStr)
								
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<SysModuleModel> CreateModelList(ref IQueryable<SysModule> queryData)
        {

            List<SysModuleModel> modelList = (from r in queryData
                                              select new SysModuleModel
                                              {
													Id = r.Id,
													Name = r.Name,
													EnglishName = r.EnglishName,
													ParentId = r.ParentId,
													Url = r.Url,
													Iconic = r.Iconic,
													Sort = r.Sort,
													Remark = r.Remark,
													Enable = r.Enable,
													CreatePerson = r.CreatePerson,
													CreateTime = r.CreateTime,
													IsLast = r.IsLast,
													Version = r.Version,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, SysModuleModel model)
        {
            try
            {
                SysModule entity = m_Rep.GetById(model.Id);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new SysModule();
               				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.EnglishName = model.EnglishName;
				entity.ParentId = model.ParentId;
				entity.Url = model.Url;
				entity.Iconic = model.Iconic;
				entity.Sort = model.Sort;
				entity.Remark = model.Remark;
				entity.Enable = model.Enable;
				entity.CreatePerson = model.CreatePerson;
				entity.CreateTime = model.CreateTime;
				entity.IsLast = model.IsLast;
				entity.Version = model.Version;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, SysModuleModel model)
        {
            try
            {
                SysModule entity = m_Rep.GetById(model.Id);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.Id = model.Id;
				entity.Name = model.Name;
				entity.EnglishName = model.EnglishName;
				entity.ParentId = model.ParentId;
				entity.Url = model.Url;
				entity.Iconic = model.Iconic;
				entity.Sort = model.Sort;
				entity.Remark = model.Remark;
				entity.Enable = model.Enable;
				entity.CreatePerson = model.CreatePerson;
				entity.CreateTime = model.CreateTime;
				entity.IsLast = model.IsLast;
				entity.Version = model.Version;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual SysModuleModel GetById(string id)
        {
            if (IsExists(id))
            {
                SysModule entity = m_Rep.GetById(id);
                SysModuleModel model = new SysModuleModel();
                              				model.Id = entity.Id;
				model.Name = entity.Name;
				model.EnglishName = entity.EnglishName;
				model.ParentId = entity.ParentId;
				model.Url = entity.Url;
				model.Iconic = entity.Iconic;
				model.Sort = entity.Sort;
				model.Remark = entity.Remark;
				model.Enable = entity.Enable;
				model.CreatePerson = entity.CreatePerson;
				model.CreateTime = entity.CreateTime;
				model.IsLast = entity.IsLast;
				model.Version = entity.Version;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
