//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.IBLL;
using Apps.IDAL;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.Models.JOB;
namespace Apps.BLL
{
	public class Virtual_JOB_TASKJOBS_LOGBLL
	{
        [Dependency]
        public IJOB_TASKJOBS_LOGRepository m_Rep { get; set; }

		public virtual List<JOB_TASKJOBS_LOGModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<JOB_TASKJOBS_LOG> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								
								a=>a.sno.Contains(queryStr)
								|| a.taskName.Contains(queryStr)
								|| a.Id.Contains(queryStr)
								
								|| a.executeStep.Contains(queryStr)
								|| a.result.Contains(queryStr)
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<JOB_TASKJOBS_LOGModel> CreateModelList(ref IQueryable<JOB_TASKJOBS_LOG> queryData)
        {

            List<JOB_TASKJOBS_LOGModel> modelList = (from r in queryData
                                              select new JOB_TASKJOBS_LOGModel
                                              {
													itemID = r.itemID,
													sno = r.sno,
													taskName = r.taskName,
													Id = r.Id,
													executeDt = r.executeDt,
													executeStep = r.executeStep,
													result = r.result,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, JOB_TASKJOBS_LOGModel model)
        {
            try
            {
                JOB_TASKJOBS_LOG entity = m_Rep.GetById(model.itemID);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new JOB_TASKJOBS_LOG();
               				entity.itemID = model.itemID;
				entity.sno = model.sno;
				entity.taskName = model.taskName;
				entity.Id = model.Id;
				entity.executeDt = model.executeDt;
				entity.executeStep = model.executeStep;
				entity.result = model.result;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, JOB_TASKJOBS_LOGModel model)
        {
            try
            {
                JOB_TASKJOBS_LOG entity = m_Rep.GetById(model.itemID);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.itemID = model.itemID;
				entity.sno = model.sno;
				entity.taskName = model.taskName;
				entity.Id = model.Id;
				entity.executeDt = model.executeDt;
				entity.executeStep = model.executeStep;
				entity.result = model.result;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual JOB_TASKJOBS_LOGModel GetById(string id)
        {
            if (IsExists(id))
            {
                JOB_TASKJOBS_LOG entity = m_Rep.GetById(id);
                JOB_TASKJOBS_LOGModel model = new JOB_TASKJOBS_LOGModel();
                              				model.itemID = entity.itemID;
				model.sno = entity.sno;
				model.taskName = entity.taskName;
				model.Id = entity.Id;
				model.executeDt = entity.executeDt;
				model.executeStep = entity.executeStep;
				model.result = entity.result;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
