//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using Apps.DEF.IBLL;
namespace Apps.DEF.BLL
{
	public partial class DEF_TestJobsDetailItemBLL: Virtual_DEF_TestJobsDetailItemBLL,IDEF_TestJobsDetailItemBLL
	{
        

	}
}
