//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using Apps.Models;
using Apps.Common;
using Microsoft.Practices.Unity;
using System.Transactions;
using Apps.BLL.Core;
using Apps.Locale;
using Apps.DEF.IDAL;
using Apps.Models.DEF;
namespace Apps.DEF.BLL
{
	public class Virtual_DEF_TestJobsDetailStepsBLL
	{
        [Dependency]
        public IDEF_TestJobsDetailStepsRepository m_Rep { get; set; }

		public virtual List<DEF_TestJobsDetailStepsModel> GetList(ref GridPager pager, string queryStr)
        {

            IQueryable<DEF_TestJobsDetailSteps> queryData = null;
            if (!string.IsNullOrWhiteSpace(queryStr))
            {
                queryData = m_Rep.GetList(
								a=>a.ItemID.Contains(queryStr)
								|| a.VerCode.Contains(queryStr)
								|| a.Code.Contains(queryStr)
								|| a.Title.Contains(queryStr)
								|| a.TestContent.Contains(queryStr)
								
								
								|| a.ResultContent.Contains(queryStr)
								
								
								|| a.Tester.Contains(queryStr)
								
								|| a.Developer.Contains(queryStr)
								
								
								
								
								
								);
            }
            else
            {
                queryData = m_Rep.GetList();
            }
            pager.totalRows = queryData.Count();
            //排序
            queryData = LinqHelper.SortingAndPaging(queryData, pager.sort, pager.order, pager.page, pager.rows);
            return CreateModelList(ref queryData);
        }
        public virtual List<DEF_TestJobsDetailStepsModel> CreateModelList(ref IQueryable<DEF_TestJobsDetailSteps> queryData)
        {

            List<DEF_TestJobsDetailStepsModel> modelList = (from r in queryData
                                              select new DEF_TestJobsDetailStepsModel
                                              {
													ItemID = r.ItemID,
													VerCode = r.VerCode,
													Code = r.Code,
													Title = r.Title,
													TestContent = r.TestContent,
													Result = r.Result,
													Sort = r.Sort,
													ResultContent = r.ResultContent,
													ExSort = r.ExSort,
													StepType = r.StepType,
													Tester = r.Tester,
													TestDt = r.TestDt,
													Developer = r.Developer,
													PlanStartDt = r.PlanStartDt,
													PlanEndDt = r.PlanEndDt,
													FinDt = r.FinDt,
													TestRequestFlag = r.TestRequestFlag,
													DevFinFlag = r.DevFinFlag,
          
                                              }).ToList();

            return modelList;
        }

        public virtual bool Create(ref ValidationErrors errors, DEF_TestJobsDetailStepsModel model)
        {
            try
            {
			    DEF_TestJobsDetailSteps entity = m_Rep.GetById(model.ItemID);
                if (entity != null)
                {
                    errors.Add(Resource.PrimaryRepeat);
                    return false;
                }
                entity = new DEF_TestJobsDetailSteps(); 
				entity.ItemID = model.ItemID;
				entity.VerCode = model.VerCode;
				entity.Code = model.Code;
				entity.Title = model.Title;
				entity.TestContent = model.TestContent;
				entity.Result = model.Result;
				entity.Sort = model.Sort;
				entity.ResultContent = model.ResultContent;
				entity.ExSort = model.ExSort;
				entity.StepType = model.StepType;
				entity.Tester = model.Tester;
				entity.TestDt = model.TestDt;
				entity.Developer = model.Developer;
				entity.PlanStartDt = model.PlanStartDt;
				entity.PlanEndDt = model.PlanEndDt;
				entity.FinDt = model.FinDt;
				entity.TestRequestFlag = model.TestRequestFlag;
				entity.DevFinFlag = model.DevFinFlag;
  

                if (m_Rep.Create(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.InsertFail);
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }



         public virtual bool Delete(ref ValidationErrors errors, string id)
        {
            try
            {
                if (m_Rep.Delete(id) == 1)
                {
                    return true;
                }
                else
                {
                    return false;
                }
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

        public virtual bool Delete(ref ValidationErrors errors, string[] deleteCollection)
        {
            try
            {
                if (deleteCollection != null)
                {
                    using (TransactionScope transactionScope = new TransactionScope())
                    {
                        if (m_Rep.Delete(deleteCollection) == deleteCollection.Length)
                        {
                            transactionScope.Complete();
                            return true;
                        }
                        else
                        {
                            Transaction.Current.Rollback();
                            return false;
                        }
                    }
                }
                return false;
            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

		
       

        public virtual bool Edit(ref ValidationErrors errors, DEF_TestJobsDetailStepsModel model)
        {
            try
            {
                DEF_TestJobsDetailSteps entity = m_Rep.GetById(model.ItemID);
                if (entity == null)
                {
                    errors.Add(Resource.Disable);
                    return false;
                }
                              				entity.ItemID = model.ItemID;
				entity.VerCode = model.VerCode;
				entity.Code = model.Code;
				entity.Title = model.Title;
				entity.TestContent = model.TestContent;
				entity.Result = model.Result;
				entity.Sort = model.Sort;
				entity.ResultContent = model.ResultContent;
				entity.ExSort = model.ExSort;
				entity.StepType = model.StepType;
				entity.Tester = model.Tester;
				entity.TestDt = model.TestDt;
				entity.Developer = model.Developer;
				entity.PlanStartDt = model.PlanStartDt;
				entity.PlanEndDt = model.PlanEndDt;
				entity.FinDt = model.FinDt;
				entity.TestRequestFlag = model.TestRequestFlag;
				entity.DevFinFlag = model.DevFinFlag;
 


                if (m_Rep.Edit(entity))
                {
                    return true;
                }
                else
                {
                    errors.Add(Resource.NoDataChange);
                    return false;
                }

            }
            catch (Exception ex)
            {
                errors.Add(ex.Message);
                ExceptionHander.WriteException(ex);
                return false;
            }
        }

      

        public virtual DEF_TestJobsDetailStepsModel GetById(string id)
        {
            if (IsExists(id))
            {
                DEF_TestJobsDetailSteps entity = m_Rep.GetById(id);
                DEF_TestJobsDetailStepsModel model = new DEF_TestJobsDetailStepsModel();
                              				model.ItemID = entity.ItemID;
				model.VerCode = entity.VerCode;
				model.Code = entity.Code;
				model.Title = entity.Title;
				model.TestContent = entity.TestContent;
				model.Result = entity.Result;
				model.Sort = entity.Sort;
				model.ResultContent = entity.ResultContent;
				model.ExSort = entity.ExSort;
				model.StepType = entity.StepType;
				model.Tester = entity.Tester;
				model.TestDt = entity.TestDt;
				model.Developer = entity.Developer;
				model.PlanStartDt = entity.PlanStartDt;
				model.PlanEndDt = entity.PlanEndDt;
				model.FinDt = entity.FinDt;
				model.TestRequestFlag = entity.TestRequestFlag;
				model.DevFinFlag = entity.DevFinFlag;
 
                return model;
            }
            else
            {
                return null;
            }
        }

        public virtual bool IsExists(string id)
        {
            return m_Rep.IsExist(id);
        }
		  public void Dispose()
        { 
            
        }

	}
}
